services:
  db:
    image: postgres:15.3
    container_name: sisaDataBase
    restart: always
    environment:
      POSTGRES_USER: daamarroquin
      POSTGRES_PASSWORD: myMarroquin
      POSTGRES_DB: sisaDataBase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
